# Generated by Django 2.0 on 2020-08-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200809_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ManyToManyField(default='India', to='rest.Country'),
        ),
    ]
